<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>TRIO2026.Simulator</AssemblyName>
    <RootNamespace>TRIO2026.Simulator</RootNamespace>
  </PropertyGroup>

</Project>
